import { Player } from '@/interfaces/Player';
import { Box, Button } from '@chakra-ui/react'
import Head from 'next/head'
import { useState } from 'react';
import { apiPOST } from '@/utils/apiUtils';

export default function Home() {
  
    const [players, setPlayers] = useState<Player[]>([
        { id: 0, name: "Lucas", number: 13, q: 2 },
        { id: 1, name: "Raul", number: 4, q: 1},
        { id: 2, name: "Esteve", number: 11, q: 2 }
    ]);

    const [parts, setParts] = useState([[0, 1, 2], [2, 1, 0], [1, 2, 0]]); // 2d number array containing player index

    const generateMatch = () => {
        const body = {
            players: players,
            nParts: 4,
            nPlayers: 6
        };

        apiPOST('match', body).then((data: any) => {
            setParts([...data.parts]);
        });
    }


    return (
        <>
            <Head>
                <title>Dev</title> <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box>
                <Button onClick={generateMatch}>Generate match</Button>
                <ul>
                    {parts.map((part: number[], partNum) => (
                        <Box key={"part" + partNum}>
                            <Box>Part {partNum+1}</Box>
                            <ul>
                                {part.map(playerIdx => (
                                    <li>{players[playerIdx].name}</li>
                                ))}
                            </ul>
                        </Box>
                    ))}
                </ul>
            </Box>
        </>
    )
}
